#!/bin/bash
INDEX=0
while [ $INDEX -lt 34 ]
do
  REMAINDER=$(( $INDEX % 2 ))
  if [ $REMAINDER -ne 0 ]
  then
    echo "<html></html>" >> $INDEX-index.html
  else
    echo "<html></html>" >> $INDEX-styleguide.html
  fi
  INDEX=$(($INDEX+1))
done